### ISSUE TITLE
Raises PHP warnings when added to a page

### ISSUE THREAD

**Issue by mudrd8mz** [sharpchi/moodle-block_coursesearch#1]
```
Warning: Creating default object from empty value in /blocks/coursesearch/block_coursesearch.php on line 74
```
Please refer to other blocks on how they handle `$this->content` . Additionally, IIRC the method `get_content()` can be actually called multiple time. So it may be checking if the content has already been generated. Again please refer to existing examples.

**Comment by sharpchi** [comment]
This should be resolved now. Thanks.
